'use strict';
document.addEventListener('DOMContentLoaded',()=>{
 const B=window.MATHEMATICS_BOOK,$=id=>document.getElementById(id);
 if(!B||!Array.isArray(B.chapters)){document.body.innerHTML='<h2 style="padding:30px;font-family:system-ui">Mathematics data could not be loaded.</h2>';return;}
 const cover=$('cover'),app=$('app'),home=$('home'),reader=$('reader'),resources=$('resources'),pages=$('pages'),modal=$('resourceModal');
 const state={term:B.terms[0]?.name||'First Term',chapter:null,lesson:0};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const key=c=>'masteryMath_'+c.term+'_'+c.title;
 const progress=c=>{try{return JSON.parse(localStorage.getItem(key(c))||'[]')}catch(e){return[]}};
 const mark=(c,i)=>{let a=progress(c);if(!a.includes(i))a.push(i);try{localStorage.setItem(key(c),JSON.stringify(a))}catch(e){}};
 function show(x){[home,reader,resources].forEach(e=>e.classList.add('hidden'));x.classList.remove('hidden');window.scrollTo(0,0)}
 function terms(){const w=$('terms');w.innerHTML='';B.terms.forEach(t=>{let b=document.createElement('button');b.className='term'+(t.name===state.term?' active':'');b.textContent=t.name;b.onclick=()=>{state.term=t.name;state.chapter=null;terms();chapters()};w.appendChild(b)})}
 function chapters(){let list=B.chapters.filter(c=>c.term===state.term);$('termTitle').textContent=state.term;$('termInfo').textContent=list.length+' chapters';let w=$('chapters');w.innerHTML='';list.forEach((c,i)=>{let done=progress(c),n=c.lessons.length,d=document.createElement('div');d.className='chapter-card';d.innerHTML=`<div class="chapter-num">${i+1}</div><div class="chapter-body"><div class="chapter-title">${esc(c.title)}</div><div class="chapter-sub">${n} lessons • long explanations • examples • practice</div><div class="progress"><i style="width:${n?done.length/n*100:0}%"></i></div></div><div class="chapter-arrow">›</div>`;d.onclick=()=>open(c,0);w.appendChild(d)})}
 function open(c,i){state.chapter=c;state.lesson=i;show(reader);render();go(i,false)}
 function content(l){let s=l.text?String(l.text).split(/\n+/).filter(Boolean).map(x=>`<p>${esc(x)}</p>`).join(''):String(l.content||'');if(l.examples?.length)s+=`<div class="section-card example"><h3>Worked Examples</h3><ol>${l.examples.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div>`;if(l.practice?.length)s+=`<div class="section-card practice"><h3>Practice Questions</h3><ol>${l.practice.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div>`;return s}
 function render(){pages.innerHTML='';state.chapter.lessons.forEach((l,i)=>{let p=document.createElement('article');p.className='lesson-page';p.innerHTML=`<div class="lesson-inner"><div class="lesson-kicker">${esc(state.chapter.term)} · Chapter ${B.chapters.filter(c=>c.term===state.chapter.term).indexOf(state.chapter)+1}</div><div class="lesson-title">${esc(l.title)}</div><div class="section-card">${content(l)}</div><div class="lesson-nav"><button class="navbtn" data-prev="${i}">← Previous</button><button class="navbtn" data-next="${i}">${i===state.chapter.lessons.length-1?'Finish chapter ✓':'Next lesson →'}</button></div></div>`;p.querySelector('[data-prev]').disabled=i===0;p.querySelector('[data-prev]').onclick=()=>go(i-1);p.querySelector('[data-next]').onclick=()=>go(i+1);pages.appendChild(p)});dots()}
 function dots(){let w=$('dots');w.innerHTML='';state.chapter.lessons.forEach((_,i)=>{let d=document.createElement('i');d.className='dot'+(i===state.lesson?' active':'');w.appendChild(d)});$('counter').textContent=`${state.lesson+1}/${state.chapter.lessons.length}`;$('readerTitle').textContent=state.chapter.title}
 function go(i,smooth=true){if(!state.chapter||i<0)return;if(i>=state.chapter.lessons.length){show(home);terms();chapters();return}state.lesson=i;pages.scrollTo({left:i*pages.clientWidth,behavior:smooth?'smooth':'auto'});mark(state.chapter,i);dots()}
 function renderResources(){let w=$('resourceCards');w.innerHTML='';(B.resources||[]).forEach((r,idx)=>{let d=document.createElement('article');d.className='resource-card';d.innerHTML=`<h3>${esc(r.title)}</h3><p>${esc(r.body||'Open this reference for more details.')}</p><div class="resource-open">Tap to open full reference →</div>`;d.onclick=()=>openResource(r);w.appendChild(d)});Object.entries(B.mocks||{}).forEach(([term,qs])=>{let d=document.createElement('article');d.className='resource-card';d.innerHTML=`<h3>📝 ${esc(term)} Mock Examination</h3><p>20 questions covering the term. Tap the card to begin.</p>`;d.onclick=()=>openMock(d,term,qs);w.appendChild(d)})}
 function openResource(r){$('modalTitle').textContent=r.title||'Study Resource';$('modalBody').textContent=r.body||'';let w=$('modalSections');w.innerHTML='';(r.sections||[]).forEach(sec=>{let box=document.createElement('section');box.className='resource-section';box.innerHTML=`<h3>${esc(sec.heading||'Reference')}</h3>`;let list=document.createElement('div');list.className=sec.heading&&/formula|symbol|notation|identity/i.test(sec.heading)?'formula-grid':'';(sec.items||[]).forEach(item=>{let el=document.createElement(list.className?'div':'ul');if(list.className)el.className='formula';else el.innerHTML=`<li>${esc(item)}</li>`;el.textContent=list.className?item:el.textContent;list.appendChild(el)});box.appendChild(list);w.appendChild(box)});modal.classList.remove('hidden');document.body.style.overflow='hidden'}
 function openMock(card,term,qs){$('modalTitle').textContent=term+' Mock Examination';$('modalBody').textContent='Answer the questions, then submit to see your score. This examination is kept inside the book and does not change your AGULIBRARY system.';let w=$('modalSections');w.innerHTML='';let form=document.createElement('div');qs.forEach((q,i)=>{let box=document.createElement('div');box.className='mock';box.innerHTML=`<b>${i+1}. ${esc(q.q)}</b>`+(q.options||[]).map((o,j)=>`<label><input type="radio" name="mock_${term}_${i}" value="${j}"> ${esc(o)}</label>`).join('');form.appendChild(box)});let btn=document.createElement('button');btn.className='navbtn';btn.textContent='Submit Examination';let result=document.createElement('div');result.className='result hidden';btn.onclick=()=>{let score=0;qs.forEach((q,i)=>{let x=form.querySelector(`input[name="mock_${term}_${i}"]:checked`);if(x&&+x.value===+q.answer)score++});result.classList.remove('hidden');result.textContent=`Result: ${score}/${qs.length} correct.`};form.append(btn,result);w.appendChild(form);modal.classList.remove('hidden');document.body.style.overflow='hidden'}
 function closeModal(){modal.classList.add('hidden');document.body.style.overflow=''}
 function theme(){let d=document.documentElement.getAttribute('data-theme')==='dark';if(d)document.documentElement.removeAttribute('data-theme');else document.documentElement.setAttribute('data-theme','dark');try{localStorage.setItem('masteryMathTheme',d?'light':'dark')}catch(e){}}
 try{if(localStorage.getItem('masteryMathTheme')==='dark')document.documentElement.setAttribute('data-theme','dark')}catch(e){}
 $('openBook').onclick=()=>{cover.classList.add('hidden');app.classList.remove('hidden');terms();chapters()};$('homeBtn').onclick=()=>{show(home);terms();chapters()};$('backChapters').onclick=()=>{show(home);terms();chapters()};$('resourcesBtn').onclick=()=>{show(resources);renderResources()};$('backLibrary').onclick=()=>{show(home);terms();chapters()};$('themeBtn').onclick=theme;$('themeBtn2').onclick=theme;$('prevBtn').onclick=()=>go(state.lesson-1);$('nextBtn').onclick=()=>go(state.lesson+1);$('closeModal').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
 pages.addEventListener('scroll',()=>{if(!pages.clientWidth)return;let i=Math.round(pages.scrollLeft/pages.clientWidth);if(i!==state.lesson&&i>=0&&i<state.chapter.lessons.length){state.lesson=i;mark(state.chapter,i);dots()}},{passive:true});
 let sx=0;pages.addEventListener('touchstart',e=>sx=e.changedTouches[0].screenX,{passive:true});pages.addEventListener('touchend',e=>{let d=e.changedTouches[0].screenX-sx;if(Math.abs(d)>60)go(state.lesson+(d<0?1:-1))},{passive:true});
 document.addEventListener('keydown',e=>{if(!modal.classList.contains('hidden')&&e.key==='Escape'){closeModal();return}if(reader.classList.contains('hidden'))return;if(e.key==='ArrowRight')go(state.lesson+1);if(e.key==='ArrowLeft')go(state.lesson-1);if(e.key==='Escape'){show(home);terms();chapters()}});
 terms();chapters();
});
